
export default new Map([
["src/content/blog/add-watermark-to-pdf.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fadd-watermark-to-pdf.mdx&astroContentModuleFlag=true")],
["src/content/blog/compress-pdf-without-losing-quality.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fcompress-pdf-without-losing-quality.mdx&astroContentModuleFlag=true")],
["src/content/blog/convert-pdf-to-images-guide.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fconvert-pdf-to-images-guide.mdx&astroContentModuleFlag=true")],
["src/content/blog/convert-word-pdf-guide.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fconvert-word-pdf-guide.mdx&astroContentModuleFlag=true")],
["src/content/blog/create-fillable-pdf-forms-guide.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fcreate-fillable-pdf-forms-guide.mdx&astroContentModuleFlag=true")],
["src/content/blog/edit-text-in-pdf-guide.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fedit-text-in-pdf-guide.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-to-merge-pdf-files.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-to-merge-pdf-files.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-to-sign-pdf-digitally.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-to-sign-pdf-digitally.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-to-split-pdf-files.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-to-split-pdf-files.mdx&astroContentModuleFlag=true")],
["src/content/blog/ocr-pdf-extract-text.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Focr-pdf-extract-text.mdx&astroContentModuleFlag=true")],
["src/content/blog/pdf-security-best-practices.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fpdf-security-best-practices.mdx&astroContentModuleFlag=true")],
["src/content/blog/smart-organize-ai-page-analysis.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fsmart-organize-ai-page-analysis.mdx&astroContentModuleFlag=true")],
["src/content/blog/smart-merge-ai-pdf-sorting.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fsmart-merge-ai-pdf-sorting.mdx&astroContentModuleFlag=true")]]);
		